# Generated by Django 3.1.7 on 2021-07-08 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('email', models.CharField(max_length=65, primary_key=True, serialize=False)),
                ('is_active', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenModel',
            fields=[
                ('nin_number', models.CharField(default='CM999999999999', max_length=15, primary_key=True, serialize=False)),
                ('sur_name', models.CharField(max_length=35)),
                ('given_name', models.CharField(max_length=35)),
                ('nationality', models.CharField(max_length=25)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('card_no', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('village', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Covid19Vaccines',
            fields=[
                ('vaccine_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dozes', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=65)),
                ('side_effects', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ug',
            fields=[
                ('dist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('email', models.CharField(max_length=65, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=65)),
                ('password', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('account_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Covid19Vaccination',
            fields=[
                ('vaccination_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('no_of_dozes', models.IntegerField(default=0)),
                ('taken_at', models.DateTimeField(null=True)),
                ('next_doze_on', models.DateTimeField(null=True)),
                ('doze_status', models.CharField(default='PARTIAL', max_length=20)),
                ('citizen_nin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='covidvms.citizenmodel')),
                ('vaccine_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='covidvms.covid19vaccines')),
            ],
        ),
    ]
