# Generated by Django 3.1.7 on 2021-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination_centers',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='covid19vaccination',
            name='vaccination_center',
            field=models.CharField(default='Mulago', max_length=50),
        ),
    ]
