# Generated by Django 3.2.5 on 2021-08-04 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidvms', '0003_alter_vaccination_centers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_staff', models.IntegerField()),
                ('email', models.CharField(max_length=65)),
                ('is_active', models.IntegerField(default=1, null=True)),
                ('date_joined', models.DateTimeField(max_length=10)),
                ('phone_NO', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='covid19vaccination',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ug',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='covid19vaccination',
            name='vaccination_district',
            field=models.ForeignKey(default=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_id', to='covidvms.ug'),
        ),
        migrations.AlterField(
            model_name='ug',
            name='dist_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='covid19vaccination',
            table='covidvms_covid19vaccination',
        ),
        migrations.AlterModelTable(
            name='ug',
            table='covidvms_ug',
        ),
    ]
