# Generated by Django 3.2.5 on 2021-08-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvms', '0004_auto_20210804_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='is_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auth_user',
            name='is_superuser',
            field=models.IntegerField(default=0),
        ),
    ]
