# Generated by Django 3.2.5 on 2021-08-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidvms', '0005_auto_20210804_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_user',
            old_name='id',
            new_name='Auth_id',
        ),
    ]
