# Generated by Django 3.2.6 on 2022-01-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvms', '0007_auto_20210807_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationCards',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_epi', models.CharField(max_length=11)),
                ('card_sn', models.CharField(max_length=8)),
                ('batch_no', models.CharField(max_length=8)),
            ],
        ),
    ]
