# Generated by Django 3.2.6 on 2022-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvms', '0008_vaccinationcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationcards',
            name='citizen_nin_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
