# Generated by Django 3.2.6 on 2022-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvms', '0009_vaccinationcards_citizen_nin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(default='Vaccine Side Effects', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='feedback',
            name='vaccination_center',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='vaccine_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
